title: "Najam Ul Saqib"
email: "najam@exfiltra.com"
description: >-
  I'm Najam, a security consultant, AppSec & CloudSec practitioner,
  FOSS enthusiast, and founder of Exfiltra, a company focused on
  making application and cloud security headache-free for engineering teams.
baseurl: ""
url: "https://njmulsqb.github.io"

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/about-us/najam.png

author:
  name: "Najam Ul Saqib"
  twitter: njmulsqb

twitter:
  username: njmulsqb
  card: summary_large_image

social:
  name: Najam Ul Saqib
  links:
    - https://www.linkedin.com/in/njmulsqb/
    - https://twitter.com/njmulsqb
    - https://github.com/njmulsqb
    - https://www.youtube.com/@cybersoldiernjm
    - https://infosec.exchange/@cybersoldier

socials:
  - name: "Email"
    url: "mailto:najam@exfiltra.com"
    icon: "fas fa-envelope"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/njmulsqb/"
    icon: "fab fa-linkedin"
  - name: "YouTube"
    url: "https://www.youtube.com/@cybersoldiernjm"
    icon: "fab fa-youtube"
  - name: "Mastodon"
    url: "https://infosec.exchange/@cybersoldier"
    icon: "fab fa-mastodon"
  - name: "Pixelfed"
    url: "https://pixelfed.social/shiningstar"
    icon: "fas fa-images"

environment: "development"

# Google Analytics 4 (GA4) Measurement ID (example: G-XXXXXXXXXX)
# Set this to enable analytics.
ga4_measurement_id:
permalink: "/:title"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives

cover_image: "/assets/img/bg/page-title.jpg"

collections:
  features:
    output: true

pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 6
  permalink: "/pages/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
  extension: "html"
  indexpage: "index"

tag_page_layout: tag-page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

feed:
  collections:
    posts:
      path: "/index.xml"
